#############################################################################
# Makefile for building: Multifunctional-DashboardApp.app/Contents/MacOS/Multifunctional-DashboardApp
# Generated by qmake (3.1) (Qt 5.12.6)
# Project:  Multifunctional-DashboardApp.pro
# Template: app
# Command: /Users/bosenatelila/Qt/5.12.6/clang_64/bin/qmake -o Makefile Multifunctional-DashboardApp.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers -I/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/macx-clang -F/Users/bosenatelila/Qt/5.12.6/clang_64/lib
QMAKE         = /Users/bosenatelila/Qt/5.12.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/bosenatelila/Qt/5.12.6/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/bosenatelila/Qt/5.12.6/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Multifunctional-DashboardApp1.0.0
DISTDIR = /Volumes/BOSENA/SPUClassWork/AppProg3220/Multifunctional-DashboardApp/.tmp/Multifunctional-DashboardApp1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/bosenatelila/Qt/5.12.6/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/bosenatelila/Qt/5.12.6/clang_64/lib -framework QtWidgets -framework QtGui -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = HttpManager.cpp \
		ToDoListModel.cpp \
		main.cpp \
		Dashboard.cpp moc_Dashboard.cpp \
		moc_HttpManager.cpp
OBJECTS       = HttpManager.o \
		ToDoListModel.o \
		main.o \
		Dashboard.o \
		moc_Dashboard.o \
		moc_HttpManager.o
DIST          = BackImg1.jpg \
		Background1.jpg \
		BckImg2.jpg \
		BckImg3.jpg \
		BckImg4.jpg \
		BckImg5.jpg \
		BckImg6.jpg \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/spec_pre.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/qdevice.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/device_config.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/unix.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/mac.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/macx.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/sanitize.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/gcc-base.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/clang.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/clang-mac.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/qconfig.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qt_functions.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qt_config.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/toolchain.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/default_pre.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/resolve_config.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/default_post.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qml_debug.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/mac.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/warn_on.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qt.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/resources.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/moc.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/uic.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/unix/thread.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qmake_use.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/file_copies.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/rez.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/exceptions.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/yacc.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/lex.prf \
		Multifunctional-DashboardApp.pro Dashboard.h \
		HttpManager.h \
		ToDoListModel.h HttpManager.cpp \
		ToDoListModel.cpp \
		main.cpp \
		Dashboard.cpp
QMAKE_TARGET  = Multifunctional-DashboardApp
DESTDIR       = 
TARGET        = Multifunctional-DashboardApp.app/Contents/MacOS/Multifunctional-DashboardApp

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Volumes/BOSENA/SPUClassWork/AppProg3220/Multifunctional-DashboardApp/Multifunctional-DashboardApp.pro


include /Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Multifunctional-DashboardApp.app/Contents/MacOS/Multifunctional-DashboardApp: ui_Dashboard.h $(OBJECTS)  
	@test -d Multifunctional-DashboardApp.app/Contents/MacOS/ || mkdir -p Multifunctional-DashboardApp.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Multifunctional-DashboardApp.pro /Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf /Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/spec_pre.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/qdevice.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/device_config.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/unix.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/mac.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/macx.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/sanitize.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/gcc-base.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/clang.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/clang-mac.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/qconfig.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qt_functions.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qt_config.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/toolchain.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/default_pre.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/resolve_config.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/default_post.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qml_debug.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/mac.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/warn_on.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qt.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/resources.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/moc.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/uic.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/unix/thread.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qmake_use.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/file_copies.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/rez.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/exceptions.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/yacc.prf \
		/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/lex.prf \
		Multifunctional-DashboardApp.pro \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Multifunctional-DashboardApp.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/spec_pre.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/qdevice.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/device_config.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/unix.conf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/mac.conf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/macx.conf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/sanitize.conf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/gcc-base.conf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/clang.conf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/common/clang-mac.conf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/qconfig.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qt_functions.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qt_config.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/sdk.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/toolchain.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/default_pre.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/resolve_config.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/default_post.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/default_post.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qml_debug.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/mac.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/warn_on.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qt.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/resources.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/moc.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/unix/opengl.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/uic.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/unix/thread.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/qmake_use.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/file_copies.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/rez.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/testcase_targets.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/exceptions.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/yacc.prf:
/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/lex.prf:
Multifunctional-DashboardApp.pro:
/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Multifunctional-DashboardApp.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

Multifunctional-DashboardApp.app/Contents/PkgInfo: 
	@test -d Multifunctional-DashboardApp.app/Contents || mkdir -p Multifunctional-DashboardApp.app/Contents
	@$(DEL_FILE) Multifunctional-DashboardApp.app/Contents/PkgInfo
	@echo "APPL????" > Multifunctional-DashboardApp.app/Contents/PkgInfo
Multifunctional-DashboardApp.app/Contents/Resources/empty.lproj: 
	@test -d Multifunctional-DashboardApp.app/Contents/Resources || mkdir -p Multifunctional-DashboardApp.app/Contents/Resources
	@touch Multifunctional-DashboardApp.app/Contents/Resources/empty.lproj
	
Multifunctional-DashboardApp.app/Contents/Info.plist: 
	@test -d Multifunctional-DashboardApp.app/Contents || mkdir -p Multifunctional-DashboardApp.app/Contents
	@$(DEL_FILE) Multifunctional-DashboardApp.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,spu.Multifunctional-DashboardApp,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},spu.Multifunctional-DashboardApp,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Multifunctional-DashboardApp,g" -e "s,@LIBRARY@,Multifunctional-DashboardApp,g" -e "s,\$${EXECUTABLE_NAME},Multifunctional-DashboardApp,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/macx-clang/Info.plist.app >Multifunctional-DashboardApp.app/Contents/Info.plist

all: Makefile \
		Multifunctional-DashboardApp.app/Contents/PkgInfo \
		Multifunctional-DashboardApp.app/Contents/Resources/empty.lproj \
		Multifunctional-DashboardApp.app/Contents/Info.plist Multifunctional-DashboardApp.app/Contents/MacOS/Multifunctional-DashboardApp

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Dashboard.h HttpManager.h ToDoListModel.h $(DISTDIR)/
	$(COPY_FILE) --parents HttpManager.cpp ToDoListModel.cpp main.cpp Dashboard.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Dashboard.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Multifunctional-DashboardApp.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h /Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Dashboard.cpp moc_HttpManager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Dashboard.cpp moc_HttpManager.cpp
moc_Dashboard.cpp: Dashboard.h \
		ToDoListModel.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QAbstractTableModel \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QTime \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		HttpManager.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		moc_predefs.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/bin/moc
	/Users/bosenatelila/Qt/5.12.6/clang_64/bin/moc $(DEFINES) --include /Volumes/BOSENA/SPUClassWork/AppProg3220/Multifunctional-DashboardApp/moc_predefs.h -I/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/macx-clang -I/Volumes/BOSENA/SPUClassWork/AppProg3220/Multifunctional-DashboardApp -I/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers -I/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Users/bosenatelila/Qt/5.12.6/clang_64/lib Dashboard.h -o moc_Dashboard.cpp

moc_HttpManager.cpp: HttpManager.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		moc_predefs.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/bin/moc
	/Users/bosenatelila/Qt/5.12.6/clang_64/bin/moc $(DEFINES) --include /Volumes/BOSENA/SPUClassWork/AppProg3220/Multifunctional-DashboardApp/moc_predefs.h -I/Users/bosenatelila/Qt/5.12.6/clang_64/mkspecs/macx-clang -I/Volumes/BOSENA/SPUClassWork/AppProg3220/Multifunctional-DashboardApp -I/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers -I/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Users/bosenatelila/Qt/5.12.6/clang_64/lib HttpManager.h -o moc_HttpManager.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_Dashboard.h
compiler_uic_clean:
	-$(DEL_FILE) ui_Dashboard.h
ui_Dashboard.h: Dashboard.ui \
		/Users/bosenatelila/Qt/5.12.6/clang_64/bin/uic
	/Users/bosenatelila/Qt/5.12.6/clang_64/bin/uic Dashboard.ui -o ui_Dashboard.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

HttpManager.o: HttpManager.cpp HttpManager.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HttpManager.o HttpManager.cpp

ToDoListModel.o: ToDoListModel.cpp ToDoListModel.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QAbstractTableModel \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/Qfile \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qfile.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QTextStream \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qtextstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ToDoListModel.o ToDoListModel.cpp

main.o: main.cpp Dashboard.h \
		ToDoListModel.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QAbstractTableModel \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QTime \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		HttpManager.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Dashboard.o: Dashboard.cpp Dashboard.h \
		ToDoListModel.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QAbstractTableModel \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QTime \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		HttpManager.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		ui_Dashboard.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QTimeZone \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qtimezone.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QDateTime \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QJsonArray \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qjsonarray.h \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		/Users/bosenatelila/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Dashboard.o Dashboard.cpp

moc_Dashboard.o: moc_Dashboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Dashboard.o moc_Dashboard.cpp

moc_HttpManager.o: moc_HttpManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HttpManager.o moc_HttpManager.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Multifunctional-DashboardApp/bin || mkdir -p $(INSTALL_ROOT)/opt/Multifunctional-DashboardApp/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Multifunctional-DashboardApp/bin/Multifunctional-DashboardApp.app
	
	-$(QINSTALL) Multifunctional-DashboardApp.app $(INSTALL_ROOT)/opt/Multifunctional-DashboardApp/bin/Multifunctional-DashboardApp.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Multifunctional-DashboardApp/bin/Multifunctional-DashboardApp.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Multifunctional-DashboardApp/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

